# TASK 2
## Amresh Prasad Sinha
## 200122009

In [108]:
!rm -r task2.csv
!wget https://github.com/AmreshSinha/Tinder-ML-with-KNN-and-Random-Forest/raw/main/task2.csv
!pip install sklearn

--2021-05-17 17:52:43--  https://github.com/AmreshSinha/Tinder-ML-with-KNN-and-Random-Forest/raw/main/task2.csv
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/AmreshSinha/Tinder-ML-with-KNN-and-Random-Forest/main/task2.csv [following]
--2021-05-17 17:52:43--  https://raw.githubusercontent.com/AmreshSinha/Tinder-ML-with-KNN-and-Random-Forest/main/task2.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 115512 (113K) [text/plain]
Saving to: ‘task2.csv’

task2.csv           100%[===================>] 112.80K  --.-KB/s    in 0.008s  

2021-05-17 17:52:43 (14.4 MB/s) - ‘task2.csv’ saved [115512/115

In [109]:
import pandas as pd
import sklearn

# Importing Dataset
df = pd.read_csv('task2.csv')
df

ID Segment type  ... Percentage It became a relationship
0     292890.8970          web  ...   0.000000                        0
1     292887.9870          web  ...   0.000000                        0
2     292894.0656       gender  ...   0.225255                        0
3     292887.1180          web  ...   0.000000                        0
4     292893.6561       gender  ...   0.211360                        0
...           ...          ...  ...        ...                      ...
1891  292887.5496          web  ...   0.000000                        0
1892  292881.6932       mobile  ...   0.312360                        0
1893  292900.8499       gender  ...   0.488025                        0
1894  292893.8600       gender  ...   0.488984                        0
1895  292890.2944          web  ...   0.000000                        0

[1896 rows x 7 columns]

In [110]:
# Replacing Null Values with 0

df.fillna(0)
df

ID Segment type  ... Percentage It became a relationship
0     292890.8970          web  ...   0.000000                        0
1     292887.9870          web  ...   0.000000                        0
2     292894.0656       gender  ...   0.225255                        0
3     292887.1180          web  ...   0.000000                        0
4     292893.6561       gender  ...   0.211360                        0
...           ...          ...  ...        ...                      ...
1891  292887.5496          web  ...   0.000000                        0
1892  292881.6932       mobile  ...   0.312360                        0
1893  292900.8499       gender  ...   0.488025                        0
1894  292893.8600       gender  ...   0.488984                        0
1895  292890.2944          web  ...   0.000000                        0

[1896 rows x 7 columns]

In [111]:
# Spliting Data

x = df.iloc[:,[3]].values
y = df.iloc[:,6].values
import numpy as np
x = np.where(x=='Yes', 1, x)
x = np.where(x=='No', 0, x)
x = np.where(x=='I don\'t use Tinder', 0.2, x)

In [112]:
x

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=object)

In [113]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=0)

In [114]:
print(x_train.shape)
print(x_test.shape)

(1422, 1)
(474, 1)


In [115]:
# KNN

from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier()

grid = {'n_neighbors':[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21], 'weights':['uniform', 'distance'],'metric':['euclidean', 'manhattan', 'minkowski']}

grid1 = GridSearchCV(estimator=model, param_grid=grid, scoring='accuracy',error_score=0)
gridsearch_result = grid1.fit(x_train, y_train)

print("Best: %f using %s" % (gridsearch_result.best_score_, gridsearch_result.best_params_))

Best: 0.649785 using {'metric': 'euclidean', 'n_neighbors': 9, 'weights': 'uniform'}


In [116]:
y_pred = gridsearch_result.predict(x_test)
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
accuracy_score(y_pred,y_test)*100

65.18987341772153

In [117]:
confusion_matrix(y_test, y_pred)

array([[290,  14],
       [151,  19]])

In [118]:
# Random Forest

from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

grid = {'n_estimators':[10, 100, 1000], 'max_features':['sqrt', 'log2']}

grid2 = GridSearchCV(estimator=model, param_grid=grid, scoring='accuracy',error_score=0)
gridsearch_result2 = grid2.fit(x_train, y_train)

print("Best: %f using %s" % (gridsearch_result2.best_score_, gridsearch_result2.best_params_))

Best: 0.645562 using {'max_features': 'sqrt', 'n_estimators': 10}


In [119]:
y_pred = gridsearch_result2.predict(x_test)
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
accuracy_score(y_pred,y_test)*100

65.61181434599156

In [120]:
confusion_matrix(y_test, y_pred)

array([[271,  33],
       [130,  40]])